FROM openjdk:8

ARG JAR_NAME
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASS

ENV JAR_TO_RUN $JAR_NAME
ENV MYSQL_HOST $DB_HOST
ENV MYSQL_DB $DB_NAME
ENV MYSQL_USER $DB_USER
ENV MYSQL_PASSWORD $DB_PASS

RUN echo $JAR_TO_RUN
RUN echo $MYSQL_HOST
RUN echo $MYSQL_DB
RUN echo $MYSQL_USER
RUN echo $MYSQL_PASSWORD

EXPOSE 8080/tcp

COPY ./$JAR_NAME /usr/src/

WORKDIR /usr/src/

CMD java -jar $JAR_TO_RUN
