name: Java CI

on:
  push:
    branches: master
#    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build
        run: ./gradlew bootJar -Dversiontag=${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: restservice-${{ github.sha }}-SNAPSHOT.jar
          path: build/libs/

  dockerbuild:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: restservice-${{ github.sha }}-SNAPSHOT.jar
      - name: Run docker builder
        run: |
          docker build -f Dockerfile --env MYSQL_HOST=${{ secrets.MYSQL_HOST }} --env MYSQL_DB=${{ secrets.MYSQL_DB }} \
          --env MYSQL_USER=${{ secrets.MYSQL_USER }} --env MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          --env JAR_NAME=restservice-${{ github.sha }}-SNAPSHOT.jar .
