name: Java CI

on:
  push:
    branches: master
#    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build
        run: ./gradlew bootJar -Dversiontag=${{ github.base_ref }}-${{ github.ref }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: restservice-${{ github.base_ref }}-${{ github.ref }}-SNAPSHOT.jar
          path: build/libs/

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/download-artifact@v1
        with:
          name: restservice-${{ github.base_ref }}-${{ github.ref }}-SNAPSHOT.jar
      - name: Run docker builder
        uses: bigstinky86/spring@master
        with:
          application-version: restservice-${{ github.base_ref }}-${{ github.ref }}-SNAPSHOT.jar
          database-host: ${{ secrets.MYSQL_HOST }}
          database-db: ${{ secrets.MYSQL_DB }}
          database-user: ${{ secrets.MYSQL_USER }}
          database-pass: ${{secrets.MYSQL_PASSWORD }}
